---
- name: Setup and deploy the environment
  hosts: all
  become: true
  vars_files:
    - vars/common.yml # Fichier de variables globales

  roles:
    - ./roles/common
    - ./roles/docker_setup
    - ./roles/npm_setup
    - ./roles/application
